baseURL = "/"
languageCode = "en"
title = "Buddhi GV"
theme = "hugo-nuo"
enableRobotsTXT = true
PygmentsCodeFences = true
canonifyurls = true

# Disqus Username
disqusShortname = "buddhigv"

# Google Analytics UA number
googleAnalytics = "UA-115034479-1"

# Copyright of your post
copyright = "© This post is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License,based on a work at http://www.buddhigv.fun，please give source if you like to quote or reproduce"


# Initial site menu, you can extend menu with content.
[[menu.main]]
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/"


[[menu.main]]
  name = "Tags"
  weight = 30
  identifier = "tags"
  url = "/tags/"

# Add your own params here
[params]
  author = "BuddhiGV"
  avatar = "/img/avatar.jpg"
  seotitle = "buddhigv fun blog"
  subtitle = "~ BuddhiGV is here to have fun ~"
  description = "BuddhiGV is here to have fun"
  paginate = 10

  # Choose your social networks
  email = "contact@buddhigv.fun"
 # github = "buddhiGV"
  twitter = "buddhiGV_fun"
  # facebook = "facebook_username"
  # google = "googlplus_id_number"
  # instagram = "instagram_username"
  youtube = "UCZ2w9dEt8WTr2Eo0sTlZMgQ"
  # vimeo = "vimeo_username"
  # medium = "medium_username"
  # quora = "quora_username"
  # dribbble = "dribbble_username"
  # behance = "behance_username"
  # jsfiddle = "jsfiddle_username"
  # codepen = "codepen_username"


  # Google Webmaster
  # https://www.google.com/webmasters/
  googleSiteVerification = "QJqXJHdI1PnOciLaJY-PFksyyYltpPnVaZU08ufWD4Q"
# <meta name="google-site-verification" content="QJqXJHdI1PnOciLaJY-PFksyyYltpPnVaZU08ufWD4Q" />
  # Bing Webmaster
  # https://www.bing.com/toolbox/webmaster/
  msValidate = "22596E34341DD1D17D6022C44647E587"
